services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - ML_SERVICE_URL=http://ml_service:8000
    depends_on:
      - ml_service
      - db

  ml_service:
    build:
      context: ./ml_service
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
