name: CI/CD Go Secure Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  security-events: write

jobs:
  ci:
    name: Build & Secure Go Application
    runs-on: ubuntu-latest

    env:
      GO_VERSION: "1.21"

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Set up Go
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # Install dependencies
      - name: Download Go modules
        run: go mod download

      #  Check formatting
      - name: Run go fmt
        run: |
          fmt_output=$(gofmt -l .)
          if [[ -n "$fmt_output" ]]; then
            echo "The following files are not formatted:"
            echo "$fmt_output"
            exit 1
          fi

      #  Lint with golangci-lint
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m

      #  Static analysis
      - name: Run go vet
        run: go vet ./...

      #  Security static analysis
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.19.0
        with:
          args: ./...

      #  Vulnerability check (govulncheck)
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          check-latest: true

      #  Docker Build
      - name: Build Docker image
        run: docker build -t beeldy-equipment:latest .

  